### ISSUE TITLE
Incorrect location for Museum National d'Histoire Naturelle (map)

### ISSUE THREAD

**Issue by philippeloret** [DiSSCo/ELViS#146] opened 2020-12-04 15:23 UTC
#### Description

As a requester, I want to know where is the 'Museum National d'Histoire Naturelle' on a map so I can visit the Museum when I go in France.

#### Steps to reproduce the issue

1. Click on 'Institutions' menu
2. Click on 'Museum National d'Histoire Naturelle'

#### What's the expected result?

- I would like to see on the map where the MNHN is in Paris.

#### What's the actual result?

- The 'Museum National d'Histoire Naturelle' is located in Great Britain and not in France.

#### Additional details / screenshot

![mnhn_map](https://user-images.githubusercontent.com/75371870/101181311-04739f00-364d-11eb-8e7d-638413c674ab.jpg)

**Comment by RBGE-Herbarium** [comment] 2020-12-08 10:07
RBGE is also incorrectly mapped

https://elvis-accept.pictura-hosting.nl/institutions/grid.426106.7

![image](https://user-images.githubusercontent.com/63307210/101469815-1b600d00-393d-11eb-9f93-34840d65c6e1.png)

**Comment by cannedit** [comment] 2020-12-08 16:17
We fetch that info from somewhere else, from CETAF if I am not mistaken (see: https://github.com/DiSSCo/ELViS/issues/66), so we have to check whether that info is correct of provide the link to the Google Map ourselves.

**Comment by mtrekels** [comment] 2020-12-10 14:31
Is the information from CETAF present as coordinates? Because the address section for an institution seems to be correct, only the point on the map is going to the city center.

**Comment by cannedit** [comment] 2020-12-11 16:56
We have seen that the information is not fetched from CETAF after all, we collect it ourselves and it has a glitch, so we will take care of this.

**Comment by cannedit** [comment] 2020-12-18 14:02
We have solved this, so please test again.

**Comment by philippeloret** [comment] 2020-12-18 14:47
This is solved for the MNHN.

**Comment by mtrekels** [comment] 2020-12-21 09:48
Tested: OK. Location on map is also changing when changing address.

**Comment by jgrieb** [comment] 2020-12-21 12:44
Tested for the institution 'Senckenberg Gesellschaft für Naturforschung': The map is not shown, which this is caused by the Nominatim returning no result for the request. However, this is a Geocoding error of Nominatim and a very specific problem, so regarding the technical setup of ELViS I would also say: OK (i.e. issue resolved because it works for the display of the other institutions). 


For those interested:
The unsuccessful request by ELViS is done like this (using API instead of UI like here):
https://nominatim.openstreetmap.org/ui/search.html?q=Senckenberganlage+25+60325+Frankfurt+am+Main
However, if the city name is written simply as 'Frankfurt' instead of 'Frankfurt am Main' it finds the correct geolocation:
https://nominatim.openstreetmap.org/ui/search.html?q=Senckenberganlage+25+60325+Frankfurt

'Frankfurt am Main' would be the official name of the city but using 'Frankfurt' as the city name works just as well because it goes with the postal code which uniquely identifies and distinguishes it from the other German city named Frankfurt as well. So if it's not too much work the city name should be changed in the database accordingly for this institution, then the map display would work as well for 'Senckenberg Gesellschaft für Naturforschung'.

**Comment by cannedit** [comment] 2020-12-22 09:21
@jgrieb changing the details of an institution is part of this test round, so please ask the VA Coordinator for Senckeberg Gesellschaft (who now also has Institution Moderator permissions) to change the address and then check whether this solves this issue for this institution too.

**Comment by mmarschler** [comment] 2020-12-22 11:59
As you already know, NHMW is also incorrectly mapped, although the address is correct.

**Comment by jgrieb** [comment] 2020-12-22 14:59
@cannedit thank you for the hint, I wrote to the VA coordinator for Senckenberg and requested to change the adress.

@mmarschler I had a short look at NHMW it looks here it is analogously an issue with how the search query is interpreted by the Nominatim search engine. Currently the query is done like 'Burgring 7 A-1010 Vienna Austria' which leads to the incorrect mapping:
https://nominatim.openstreetmap.org/ui/search.html?q=Burgring+7+A-1010+Vienna+Austria
However, when querying for 'Burgring 7, A-1010 Vienna Austria' it seems to work, doesn't it?:
https://nominatim.openstreetmap.org/ui/search.html?q=Burgring+7%2C+A-1010+Vienna+Austria

@cannedit maybe the search query could be created with a comma separating the street (+number) and the postal code, so that the query is interpreted better? Just an idea...

**Comment by mmarschler** [comment] 2020-12-22 16:15
@jgrieb: You're right - 'Burgring 7, A-1010 Vienna Austria' works perfectly well!

**Comment by cannedit** [comment] 2020-12-23 10:31
Ok, since this has been solved for about 99% of the cases (and for the other 1% there is a workaround: change the address) I will close this ticket and create a new one for finetuning this later on, whenever we have time for that.

**Closed as completed by cannedit** 2020-12-23 10:31 UTC
Labels: bug, to test, resolved, Institutions issue
