### ISSUE TITLE
TA: Show only requests for my institution doesn't work

### ISSUE THREAD

**Issue by mmarschler** [DiSSCo/ELViS#188] opened 2021-02-08 12:58 UTC
#### Description
When I'm logged in as a TA coordinator and go to requests, I see all requests including the ones for my institution. When I filter them by clicking "Show only requests for my institution" I don't see a single request.

#### Steps to reproduce the issue

1.  Log in as TA coordinator or institutional moderator
2. Go to tab "requests"
3. Filter "Show only requests for my institution"

#### What's the expected result?

- see all requests for my institution

#### What's the actual result?

- no requests found

#### Additional details / screenshot
![ELViS_all_requests_2021-02-08](https://user-images.githubusercontent.com/75616869/107222761-9f09a900-6a15-11eb-8097-467576580a69.PNG)
![ELViS_requests_my_inst_2021-02-08](https://user-images.githubusercontent.com/75616869/107222856-bea0d180-6a15-11eb-8674-334977373f5c.PNG)

**Comment by cannedit** [comment] 2021-02-09 10:00
This is probably due to a mixture of roles; we will look into this.

**Comment by cannedit** [comment] 2021-02-16 12:10
We're still working on the handling of TA requests, so this will be fixed during the next sprint.

**Comment by cannedit** [comment] 2021-03-09 11:49
This has been taken care of, please test.

**Comment by mmarschler** [comment] 2021-03-10 19:02
it works fine now.

**Closed as completed** 2021-03-10 20:00 UTC
Labels: bug, to test, resolved

**Comment by falkogloeckler** [comment] 2021-03-11 08:28
Did someone test it with the "TA coordinator" role or with the "institutional moderator" role only? 
According to feedback I got, the filter "Show only requests for my institution" is not displayed for our TA coordinator (MfN). 
She is also a institutional moderator. If the issue is due to a mixture of roles, does this have to be solved per account? 
Thanks for any advice!

**Comment by mmarschler** [comment] 2021-03-11 08:40
It tested it with our general account, which has all roles (TA coord., VA coord. and inst. mod.).
