### ISSUE TITLE
deleted facility still shown on the facility list

### ISSUE THREAD

**Issue by mmarschler** [DiSSCo/ELViS#185] opened 2021-02-08 09:44 UTC
When you delete a facility, it still can be seen on the facility list. It vanishes only after refreshing the page or go to another tab.

#### Steps to reproduce the issue

1.  Klick the button "delete facility"
2. Conform the question "Are you sure you want to delete the facility" -> delete
3. The deleted facility is still shown on the list.
4a. It only vanishes after refreshing the page or go to another tab on the top of the page (going to "institutions", "people" or "collections" in the institutions page is not enough!).
4b. You can even go to "edit facilty" and make changes of a deleted facility. By clicking the "save facility" button (you can do that withour error!) you come to the "institution"-page automatically. When you click on "facility", the deleted facility has vanished.

#### What's the expected result?

- The deleted facility vanishes immediatly from the facilty-list after deleting it.

#### What's the actual result?

- see above

**Comment by cannedit** [comment] 2021-02-09 09:56
Can you please provide more info on this (because I can't reproduce it): in which browser/version did you run into this and does it also happen in another browser/version?

**Comment by mmarschler** [comment] 2021-02-09 11:39
Yesterday I tested on my computer at work, Firefox 85.0.1 (64-Bit).
Today I tested on my private computer, same problem. Firefox 82.0.3 (64-Bit).

**Comment by cannedit** [comment] 2021-02-09 17:46
We will look into this.

**Comment by cannedit** [comment] 2021-02-16 12:11
This is fixed now, please test.

**Comment by LarissaS** [comment] 2021-02-18 08:39
I can't delete anything, it says "action disabled due to active TA call"

**Comment by cannedit** [comment] 2021-02-18 08:53
Please try again, but make sure there is no TA Call active at the moment you try, because that's the trigger for not allowing to edit or delete facilities anymore (check the manual).

**Comment by LarissaS** [comment] 2021-02-18 09:27
It works now, probably I put the link in the title of Instruments instead of in the description field. May be to make it clear the "URL" field should be added, the same as for Facility?

**Comment by cannedit** [comment] 2021-02-18 15:03
@LarissaS I guess your last comment belongs to another Github issue?

**Comment by LarissaS** [comment] 2021-02-19 07:10
indeed, sorry! I'll copy it on right place.

**Comment by philippeloret** [comment] 2021-02-19 09:49
Now, we can't delete facility when a TA Call is active. 
But I can add a new facility. I wonder if it is a good idea to let institution moderator add a facility if we can't edit or delete this new facility because institution moderator can make errors but can't resolve them.

**Comment by cannedit** [comment] 2021-02-19 11:23
@philippeloret I understand your concern, but allowing to add a new facility when a TA Call is active is only meant to be used in case an Institution Moderator forgot to add a facility which will block a request for a visit (remember the VA workflow: over there it's not possible to add an institution to a request once it's submitted); so this is just in case of an emergency; allowing also editing an deleting facilities while a TA Call is active is far more risky than this and I  hope you agree?

**Comment by philippeloret** [comment] 2021-02-19 12:45
@cannedit I agree, it is really risky to delete facilities while a TA Call is active. And normally, all facilities have to be added before TA Call and there is no reason to add a facility, so it is not really important. But as the feature exists, institution moderators should be aware about this concern.

**Comment by mmarschler** [comment] 2021-03-01 08:44
sorry, I still can't test it, as the test-TA call ends on 25.3.

**Comment by falkogloeckler** [comment] 2021-03-11 08:20
Same here. Can't test deleting facility, probably due to existing test-TA call

**Comment by cannedit** [comment] 2021-03-11 08:46
Then please organise together with an admin (@scottwilson-nhm) to have a timeslot during which calls are closed to test this.

**Comment by wouteraddink** [comment] 2021-03-11 08:55
Facilities will not be deleted during the call, so it is not a major problem if this issue cannot be closed now.

**Comment by cannedit** [comment] 2021-03-11 10:11
I have just closed the open TA call a few minutes ago, so please test again and let me know asap whether I can open it again for other testers/test scenario's.

**Comment by mmarschler** [comment] 2021-03-11 10:24
Just tested - it works now! The deleted facility vanished immediately from the list.

**Comment by LarissaS** [comment] 2021-03-11 10:28
Tested - it works. 
But my institutional page is empty and I can't do anything with it. I added information last week and it's vanished. 
![image](https://user-images.githubusercontent.com/949726/110773319-e5dcff80-825c-11eb-956a-f6a3746a5158.png)

**Comment by cannedit** [comment] 2021-03-11 10:32
@mmarschler Ok, thanks, I have activated the call again.

@LarissaS the additional issue is already reported before and we're working on this.

**Closed as completed** 2021-03-11 17:20 UTC
Labels: bug, to test, resolved, feedback
