### ISSUE TITLE
Add/delete user to institutional profile, small bug?

### ISSUE THREAD

**Issue by LarissaS** [DiSSCo/ELViS#184] opened 2021-02-05 13:36 UTC
#### Description
When I add or delete Arnaud Henrard, who is an institutional coordinator for RMCA, a line with information about him does not appear/disappear after the action. I have to refresh the page. With other users it works fine. 

#### Steps to reproduce the issue

1.  I added Arnaud and Andrea
2. 
3. 

#### What's the expected result?

-to see both names op the People page 

#### What's the actual result?
only Andrea appears (screenshot1), Arnaud is missing but after refreshing his name appears too (screenshot 2). The same when I remove Arnaud. 
-

#### Additional details / screenshot
![image](https://user-images.githubusercontent.com/949726/107040160-1e516f80-67bf-11eb-90c1-790beed466fd.png)
![image](https://user-images.githubusercontent.com/949726/107040344-653f6500-67bf-11eb-9828-094c75d579d8.png)

**Comment by cannedit** [comment] 2021-02-09 09:55
Yes, immediate update of the info when editing the profile seems to be a problem; we're looking into this at the moment; for now. please check whether logging out/logging in again (and sometimes empty the browser cache) is a good workaround; let me know whether that works.

**Comment by LarissaS** [comment] 2021-02-09 13:18
I tried another browser (Chrome) and emptied the browser cache, but still the same problem with adding/removing Arnaud. With other people (I tried Patricia Mergen) it works absolutely fine. It has probably something to do with the fact that Arnaud is an institutional coordinator!

**Comment by cannedit** [comment] 2021-02-16 12:12
This is fixed now, please test.

**Comment by LarissaS** [comment] 2021-02-16 14:08
It works fine with adding/deleting other people, but not coordinators: I tried to delete Arnaud or myself, it askes "Are you sure you want to remove this person", but  nothing happens after I push 'Yes'.

**Comment by cannedit** [comment] 2021-02-16 20:14
Ok, I could reproduce this and we will take care of this.

**Comment by cannedit** [comment] 2021-03-09 11:50
This has been taken care of, please test.

**Comment by LarissaS** [comment] 2021-03-09 13:14
Logged in as coordinator I can add/delete other people but I can't delete neither Arnaud coordinator nor Larissa. After I push "delete" I get a message "Are you sure you want to remove this person", but nothing happens after I push 'Yes'.
![image](https://user-images.githubusercontent.com/949726/110475744-90301800-80e1-11eb-833e-6f5217c1cf42.png)

**Comment by cannedit** [comment] 2021-03-09 14:17
@LarissaS this is strange: as (TA) coordinator you should not be able to add/delete users and frankly I can't reproduce this, so would you please check again, because this might be a glitch because of the recent deployment.
As for not being able to delete Arnaud and yourself, that's natural behaviour: you can't delete yourself and you can't delete an Institution Moderator.

**Comment by LarissaS** [comment] 2021-03-09 14:30
No no, I was logged in as Arnaud (coordinator)!

**Comment by cannedit** [comment] 2021-03-09 14:37
Ehm, so as Institution Moderator you mean?
Well then it's obvious that you could add/edit users, and also that you couldn't remove Arnaud, because you were logged in as him.
Furthermore - since we now have more elaborate roles assignment by an Admin - as Institution Moderator you can only delete the users you have added yourself, so for deleting others - as assigned by an Admin - you have to ask an Admin to remove those users.

**Comment by LarissaS** [comment] 2021-03-09 14:39
Fine to me

**Comment by LarissaS** [comment] 2021-03-11 08:28
By chance I added Carol Paleco to RMCA institutional profile and I can't delete her anymore. With other people it works.

**Comment by mmarschler** [comment] 2021-03-11 11:51
I could reproduce Larissas issue:
I am logged in as inst. moderator and added a user to our institution. I have no problems to remove this user afterwards when shes only a requester.
But if I assign a role to her (e. g. TA coordinator), it is not possible to remove this user anymore.

But I think this is quite a good protection so that coordinators cannot be removed by mistake. You just have to withdraw the coordinator-role and can remove the user afterwords. I think this is a good approach!

**Comment by cannedit** [comment] 2021-03-11 12:13
@mmarschler thanks, and yes, I looked into her test scenario also and I could delete that specific user when logged in as an admin, so I don't thinks this is a showstopper, there's a workaround if needed.

**Comment by LarissaS** [comment] 2021-03-11 12:28
The strange thing is that I did not assign a role to her! She was already a TA coordinator for RBINS. But I also tried with Patricia (TA coord. for Meise) and with Patrick Semal (TA and VA and inst. coord. for RBINS) and I could delete them without any problem. And Carol not! 
Of course is was just a test, in normal situation I would not add people who should not be on our institutional page.

**Comment by cannedit** [comment] 2021-03-11 13:01
@LarissaS Ok, thanks for the info and connecting/disconnecting people to an institution and assigning roles should not happen that often and should ideally be dealt with before starting a call.

**Closed as completed** 2021-03-11 17:22 UTC
Labels: bug, to test, resolved
